os: linux
dist: xenial
group: beta
language: node_js
node_js:
  - "12"

cache:
  directories:
    - node_modules

jobs:
  fast_finish: true
  allow_failures:
    - env: SOLC_NIGHTLY=true
  include:
    - stage: tests
      name: "Linter"
      script: npm run lint

    - stage: tests
      name: "Unit tests (using Truffle)"
      script: npm run test

    - stage: tests
      name: "Unit tests (using Buidler)"
      script: npm run buidler:test

    - stage: tests
      name: "Unit tests with coverage report"
      script: npm run coverage

    - stage: tests
      name: "Unit tests using solc nightly"
      script: npm run test
      env: SOLC_NIGHTLY=true
